apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-port
  namespace: kafka
spec:
  selector:
    strimzi.io/cluster: my-connect-cluster
    strimzi.io/kind: KafkaConnect
    strimzi.io/name: my-connect-cluster-connect
  type: NodePort
  ports:
    - name: http
      port: 8083
      targetPort: 8083
